sonar.projectKey=full-stack-fastapi
sonar.projectName=full-stack-fastapi
sonar.projectVersion=1.0

# Backend
sonar.sources=backend/app
sonar.tests=backend/app/tests
sonar.python.coverage.reportPaths=backend/coverage.xml

# Frontend
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
